/// Every command that `src/lib.rs` registers with `tauri::generate_handler!`.
///
/// With an app manifest, Tauri checks each application command against the capabilities, as
/// it checks the commands of a plugin: a window may call a command only when one of its
/// capabilities grants `allow-<command>` (with `-` for `_`). Without a manifest, every window
/// could call every command, so the Settings window could quit the application without the
/// quit decision of ADR 027, start an export, or import a file.
///
/// `tauri-build` writes the `allow-` and `deny-` permission of each name here into
/// `permissions/autogenerated`. The test `every_registered_command_has_a_permission_decision`
/// in `src/lib.rs` compares this list with the registration and with the two capabilities.
const APP_COMMANDS: &[&str] = &[
    "start_capability_probe",
    "start_export",
    "cancel_export",
    "cancel_active_export",
    "reveal_export_output",
    "import_media",
    "read_source_revision",
    "load_project",
    "save_project",
    "confirm_quit",
    "load_settings",
    "save_settings",
    "restore_default_presets",
    "reset_settings",
    "open_settings_window",
    "take_settings_window_request",
    "close_settings_window",
];

fn main() {
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    // `tauri_build::build` does the same with the default attributes: it prints the error,
    // which cargo shows, and fails the build.
    if let Err(error) = tauri_build::try_build(attributes) {
        println!("{error:#}");
        std::process::exit(1);
    }
}
