/**
 * Domain and wire types for media export rendering in QuipClip.
 *
 * Implements wire contract for `start_export`, `cancel_export`, and `export:progress` events.
 * See ADR 002, ADR 004, ADR 011, and ADR 014.
 */

import type { Pts, Rational } from "@/types/project";

/**
 * Half-open interval [inPts, outPts) marking an export segment boundary
 * aligned to source video presentation timestamps (PTS).
 */
export type ExportSegmentBoundary = { inPts: Pts; outPts: Pts };

/**
 * Request payload sent to the backend `start_export` command.
 */
export type ExportRequest = {
  sourcePath: string;
  outputPath: string;
  segments: ExportSegmentBoundary[];
  presetId?: string;
};

/**
 * Immediate payload returned when `start_export` starts.
 */
export type ExportStart = {
  runId: string;
  presetId: string;
  outputPath: string;
  segmentCount: number;
  totalDurationUs: number;
  expectedFrames?: number;
};

/**
 * Stable backend error codes returned by the Rust export commands verbatim
 * or emitted in `failed` export events.
 */
export const BACKEND_EXPORT_ERROR_CODES = [
  "appDataUnavailable",
  "settingsUnreadable",
  "presetNotFound",
  "ffmpegPairMissing",
  "ffprobeSpawnFailed",
  "ffprobeProcessFailed",
  "ffprobeParseFailed",
  "ffprobeTimedOut",
  "noSegments",
  "tooManySegments",
  "invalidSegment",
  "sourcePathInvalid",
  "sourceNotFound",
  "sourceNotFile",
  "outputPathInvalid",
  "outputDirectoryMissing",
  "outputEqualsSource",
  "outputNotWritable",
  "sourceFrameRateUnknown",
  "sourceAudioRateUnknown",
  "encoderUnavailable",
  "ffmpegSpawnFailed",
  "ffmpegProcessFailed",
  "frameCountMismatch",
  "outputRenameFailed",
  "canceled",
  "commandExecutionFailed",
  "exportAlreadyRunning",
] as const;

export type BackendExportErrorCode = (typeof BACKEND_EXPORT_ERROR_CODES)[number];

/**
 * Frontend error codes generated by client-side operations such as dialog failures.
 *
 * These must NEVER enter `BACKEND_EXPORT_ERROR_CODES`: `types.test.ts` reads the Rust
 * `export_error_codes!` invocation and asserts that list is set-equal to the Rust vocabulary,
 * and the backend emits none of these.
 *
 * `sourceRevisionChanged` is a confirmation and not a terminal failure. The export flow raises
 * it when the file on disk is no longer the revision the segments were marked against, and the
 * export dialog renders it with three actions rather than as an error the user can only close.
 */
export const FRONTEND_EXPORT_ERROR_CODES = [
  "dialogFailed",
  "sourceRevisionChanged",
] as const;

export type FrontendExportErrorCode = (typeof FRONTEND_EXPORT_ERROR_CODES)[number];

/**
 * Complete set of export error codes supported by the frontend,
 * including backend error codes, frontend dialog codes, and the fallback code "unknown".
 */
export const EXPORT_ERROR_CODES = [
  ...BACKEND_EXPORT_ERROR_CODES,
  ...FRONTEND_EXPORT_ERROR_CODES,
  "unknown",
] as const;

export type ExportErrorCode = (typeof EXPORT_ERROR_CODES)[number];

/**
 * Options for constructing an ExportError instance.
 */
export type ExportErrorOptions = {
  code: ExportErrorCode;
  detail?: string;
  exitCode?: number;
  encoder?: string;
};

/**
 * Normalized error structure returned when export operations fail.
 */
export class ExportError extends Error {
  /** Stable semantic error code for localization and error classification. */
  readonly code: ExportErrorCode;
  /** Optional raw diagnostic text from the operating system or ffmpeg stderr. */
  declare readonly detail?: string;
  /** Optional integer process exit code when ffmpeg execution fails. */
  declare readonly exitCode?: number;
  /** Optional encoder name if failure was related to a specific encoder. */
  declare readonly encoder?: string;

  constructor(options: ExportErrorOptions) {
    super(options.detail ? `${options.code}: ${options.detail}` : options.code);
    this.name = "ExportError";
    this.code = options.code;
    if (options.detail !== undefined) {
      this.detail = options.detail;
    }
    if (options.exitCode !== undefined) {
      this.exitCode = options.exitCode;
    }
    if (options.encoder !== undefined) {
      this.encoder = options.encoder;
    }
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

/**
 * Event emitted when media export execution starts.
 */
export type ExportStartedEvent = {
  event: "started";
  runId: string;
  outputPath: string;
  segmentCount: number;
  totalDurationUs: number;
  expectedFrames?: number;
};

/**
 * Event emitted during media export execution to report frame progress.
 *
 * NOTE: There is deliberately NO out-time field on progress.
 * ADR 014 measurement 12 found ffmpeg's out_time_us wrong when -copyts is set,
 * so progress is frame-based. fps and speed are Rational numbers.
 */
export type ExportProgressUpdateEvent = {
  event: "progress";
  runId: string;
  frame: number;
  expectedFrames?: number;
  fps?: Rational;
  speed?: Rational;
  totalSize?: number;
};

/**
 * Event emitted when ffmpeg execution has completed and the output file is being published.
 *
 * This phase begins after ffmpeg has exited successfully, the frame count has been verified,
 * and the cancel flag has been re-checked. Nothing is being encoded or processed at this stage.
 * All that remains is renaming the finished temporary file over the destination, which on
 * Windows can wait seconds while a virus scanner reads back a multi-gigabyte file.
 *
 * Note that `-movflags +faststart` is a genuine post-write pass: the flag is set for the MP4 and MOV
 * containers and not for Matroska, and where it is set it runs inside ffmpeg before the process
 * exits. That is why this phase is not called "finalizing" or "post-processing".
 *
 * The user interface must NOT show the word "publishing" -- it renders as "Finishing...".
 * That is the ADR 011 split: a stable code crosses the boundary, the frontend translates.
 */
export type ExportPublishingEvent = {
  event: "publishing";
  runId: string;
};

/**
 * Event emitted when media export completes successfully.
 *
 * NOTE: There is deliberately NO out-time field on finished.
 * ADR 014 measurement 12 found ffmpeg's out-time wrong under -copyts,
 * so an out-time field was deliberately omitted for the same reason as on progress.
 * A consumer wanting a duration must use the plan-derived totalDurationUs from started.
 */
export type ExportFinishedEvent = {
  event: "finished";
  runId: string;
  outputPath: string;
  frames: number;
};

/**
 * Event emitted when media export fails on the backend worker.
 */
export type ExportFailedEvent = {
  event: "failed";
  runId: string;
  code: BackendExportErrorCode;
  detail?: string;
  exitCode?: number;
  encoder?: string;
};

/**
 * Tagged union of all possible backend events emitted on `export:progress`.
 */
export type ExportProgressEvent =
  | ExportStartedEvent
  | ExportProgressUpdateEvent
  | ExportPublishingEvent
  | ExportFinishedEvent
  | ExportFailedEvent;

/**
 * Output status states supported by the export store.
 */
export const EXPORT_STATUSES = [
  "idle",
  "preparing",
  "running",
  "publishing",
  "finished",
  "canceled",
  "failed",
] as const;

export type ExportStatus = (typeof EXPORT_STATUSES)[number];

/**
 * Public serializable state of the export store.
 */
export type ExportState = {
  /** Current lifecycle status of the export operation. */
  status: ExportStatus;
  /** Identifier of the active export run, or null if idle or reset. */
  runId: string | null;
  /** Destination output file path, or null if unconfigured. */
  outputPath: string | null;
  /** Number of segments included in the active export request. */
  segmentCount: number;
  /**
   * Latest reported frame count from ffmpeg progress.
   * Recorded during export but not rendered in UI yet:
   * the percentage bar becomes a view-only change later.
   */
  frame: number | null;
  /**
   * Expected total frame count computed during planning.
   * Recorded during export but not rendered in UI yet:
   * the percentage bar becomes a view-only change later.
   */
  expectedFrames: number | null;
  /** Last error encountered during export, or null if idle or succeeded. */
  error: ExportError | null;
};

/**
 * Actions provided by the export store.
 */
export type ExportActions = {
  /**
   * Subscribes to backend export progress events and starts the export.
   *
   * @param request The export parameters and segment boundaries.
   * @returns The initial export start payload, or null on failure.
   */
  startExport: (request: ExportRequest) => Promise<ExportStart | null>;
  /**
   * Signals the backend to cancel the active export run.
   *
   * @returns True if cancellation was requested, false otherwise.
   */
  cancelExport: () => Promise<boolean>;
  /**
   * Resets the store back to its initial idle state.
   */
  reset: () => void;
  /**
   * Ensures an active subscription to the `export:progress` event channel.
   */
  ensureSubscribed: () => Promise<void>;
  /**
   * Unsubscribes from backend export progress events.
   */
  unsubscribe: () => void;
  /**
   * Entry point for recording frontend-only errors (such as `dialogFailed`),
   * allowing client-side failures to render through exactly the same path as
   * a backend failure. The store normalizes the error through `normalizeExportError`,
   * matching the media and settings slices.
   *
   * @param error The raw error to normalize and record in the store.
   */
  reportError: (error: unknown) => void;
};

/**
 * Combined type of the export store state and actions.
 */
export type ExportStoreState = ExportState & ExportActions;
