/**
 * Domain and wire types for application settings and export presets in QuipClip.
 *
 * Implements wire contract for settings commands and on-disk settings schema (ADR 013).
 */

import type { Rational, Resolution } from "@/types/project";

/**
 * The canonical schema version for settings.json.
 */
export const SETTINGS_SCHEMA_VERSION = 1;

/**
 * Output container formats supported by export presets.
 * Closed set matching the Rust `Container` enum.
 */
export const PRESET_CONTAINERS = ["mp4", "mov", "mkv"] as const;

export type PresetContainer = (typeof PRESET_CONTAINERS)[number];

/**
 * Quality control strategies supported by export presets.
 * Closed set matching the Rust `QualityKind` enum.
 */
export const QUALITY_KINDS = ["crf", "bitrate", "qualityScale"] as const;

export type QualityKind = (typeof QUALITY_KINDS)[number];

/**
 * Preset quality configuration.
 *
 * On the Rust backend, `value` is an unsigned 32-bit integer (`u32`).
 * When `kind === "bitrate"`, `value` counts KILOBITS PER SECOND (kbps),
 * not bits per second.
 *
 * Valid ranges enforced by backend validation:
 * - crf: 0..=63 (lower is higher quality)
 * - bitrate: 1..=200_000 (kilobits per second)
 * - qualityScale: 1..=100 (encoder-defined scale)
 */
export type PresetQuality = {
  kind: QualityKind;
  /**
   * Non-negative integer quality value.
   * When `kind` is "bitrate", this counts KILOBITS PER SECOND (kbps).
   */
  value: number;
};

/**
 * Output resolution setting for an export preset.
 * Either the literal "source" string to preserve source dimensions,
 * or an explicit width and height in pixels.
 */
export type PresetResolution = "source" | Resolution;

/**
 * Output frame rate setting for an export preset.
 * Either the literal "source" string to preserve source frame rate,
 * or an explicit positive rational rate.
 */
export type PresetFrameRate = "source" | Rational;

/**
 * Single export preset definition matching the Rust `Preset` wire schema.
 */
export type Preset = {
  id: string;
  name: string;
  container: PresetContainer;
  videoEncoder: string;
  audioEncoder: string;
  quality: PresetQuality;
  resolution: PresetResolution;
  frameRate: PresetFrameRate;
};

/**
 * Application settings document stored at `<app_data>/settings.json` (schema version 1).
 *
 * `ffmpegPath` and `activePresetId` are absent when unset, never null.
 */
export type Settings = {
  schemaVersion: 1;
  ffmpegPath?: string;
  presets: Preset[];
  activePresetId?: string;
};

/**
 * Stable backend error codes returned by the Rust settings commands verbatim.
 */
export const BACKEND_SETTINGS_ERROR_CODES = [
  "appDataUnavailable",
  "readFailed",
  "permissionDenied",
  "writeFailed",
  "invalidJson",
  "invalidSettings",
  "unsafeSettingsValue",
  "futureSchemaVersion",
  "settingsUnreadable",
  "backupFailed",
  "invalidPath",
  "commandExecutionFailed",
] as const;

export type BackendSettingsErrorCode = (typeof BACKEND_SETTINGS_ERROR_CODES)[number];

/**
 * Frontend error codes generated by client-side operations such as dialog failures.
 */
export const FRONTEND_SETTINGS_ERROR_CODES = ["dialogFailed"] as const;

export type FrontendSettingsErrorCode = (typeof FRONTEND_SETTINGS_ERROR_CODES)[number];

/**
 * Complete set of settings error codes supported by the frontend,
 * including backend codes, frontend dialog codes, and the fallback code "unknown".
 */
export const SETTINGS_ERROR_CODES = [
  ...BACKEND_SETTINGS_ERROR_CODES,
  ...FRONTEND_SETTINGS_ERROR_CODES,
  "unknown",
] as const;

export type SettingsErrorCode = (typeof SETTINGS_ERROR_CODES)[number];

/**
 * Options for constructing a SettingsError instance.
 */
export type SettingsErrorOptions = {
  code: SettingsErrorCode;
  detail?: string;
  field?: string;
  value?: string;
  foundSchemaVersion?: number;
  supportedSchemaVersion?: number;
};

/**
 * Normalized error structure returned when settings operations fail.
 */
export class SettingsError extends Error {
  /** Stable semantic error code for localization and error classification. */
  readonly code: SettingsErrorCode;
  /** Optional raw diagnostic text from the operating system or Tauri rejection. */
  declare readonly detail?: string;
  /** Optional dotted field path identifying which property violated validation invariants. */
  declare readonly field?: string;
  /** Optional stringified value representing unsafe or rejected inputs. */
  declare readonly value?: string;
  /** Optional schema version number found in the document when rejected for future version. */
  declare readonly foundSchemaVersion?: number;
  /** Optional schema version number supported by this build. */
  declare readonly supportedSchemaVersion?: number;

  constructor(options: SettingsErrorOptions) {
    super(options.detail ? `${options.code}: ${options.detail}` : options.code);
    this.name = "SettingsError";
    this.code = options.code;
    if (options.detail !== undefined) {
      this.detail = options.detail;
    }
    if (options.field !== undefined) {
      this.field = options.field;
    }
    if (options.value !== undefined) {
      this.value = options.value;
    }
    if (options.foundSchemaVersion !== undefined) {
      this.foundSchemaVersion = options.foundSchemaVersion;
    }
    if (options.supportedSchemaVersion !== undefined) {
      this.supportedSchemaVersion = options.supportedSchemaVersion;
    }
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

/**
 * Result payload returned from a successful `load_settings` backend invocation.
 */
export type LoadSettingsResult = {
  settings: Settings;
  seeded: boolean;
};

/**
 * Lifecycle status of the settings store.
 */
export type SettingsStatus = "idle" | "loading" | "saving" | "ready" | "error";

/**
 * Public serializable state of the settings store.
 */
export type SettingsState = {
  /** Current lifecycle status. */
  status: SettingsStatus;
  /** Current loaded settings document, or null if uninitialized. */
  settings: Settings | null;
  /** Whether the settings document was seeded from defaults because no file existed. */
  seeded: boolean;
  /** Last error encountered during settings operations, or null if idle or ready. */
  error: SettingsError | null;
};

/**
 * Actions provided by the settings store.
 */
export type SettingsActions = {
  /**
   * Loads settings from the backend, seeding defaults in memory if no settings file exists yet.
   */
  loadSettings: () => Promise<LoadSettingsResult | null>;
  /**
   * Validates and saves updated settings to disk.
   */
  saveSettings: (settings: Settings) => Promise<Settings | null>;
  /**
   * Restores default presets over current library while preserving custom presets and configuration.
   */
  restoreDefaultPresets: () => Promise<Settings | null>;
  /**
   * Moves any damaged settings file aside and writes fresh default seed presets.
   */
  resetSettings: () => Promise<Settings | null>;
  /**
   * Reports an error to the settings store.
   */
  reportError: (error: unknown) => void;
  /**
   * Resets the store back to its initial idle state.
   */
  reset: () => void;
};

/**
 * Combined type of the settings store state and actions.
 */
export type SettingsStoreState = SettingsState & SettingsActions;
